services:
  django:
    build:
      context: .
    image: dwitareas:app
    ports:
      - "8000:8000"
    volumes:
      - ./Frontend:/app/Frontend
    command: python manage.py runserver 0.0.0.0:8000

  fastapi:
    image: dwitareas:app
    ports:
      - "8800:8800"
    working_dir: /app/dwi-tareasapi
    volumes:
      - ./dwi-tareasapi:/app/dwi-tareasapieasapi
    command: uvicorn mongoapi:app --host 0.0.0.0 --port 8800 --reload
